blockchain/contracts/Knowtfolio.sol

- articleId => tokenID のmappingを作成した
- mintする際に、articleIdを引数に入れた
- articleIdは１文字以上の文字列
- mintする際に、mapの衝突をチェックした上で、mapにarticleIdをtokenIdを保存する
- isOwnerOfArticleでarticleIdとaddressから編集権があるかチェック

contractの修正

---

Makefile
README.md
docker-compose.yml
server/Dockerfile
server/main.go

docker-composeのサービスに`server`を追加し、`make server`でGoa の自動生成、DBの起動、サーバのきどうまで全て行えるようになった

ServerをDockerで立ち上げられるように

---

Makefile

`server`起動前に、`goa`ファイルを自動生成する

---

Makefile
docker-compose.yml
server/Dockerfile
server/main.go

* docker-composeのターゲットに`server`を追加
* バックエンドコードで、DBのホストネームを`localhost`から`db`（コンテナ上からはこうアクセスする必要がある）に変更
* makeでもサーバを起動できるように

バックエンドのDockerサービス化

---

Makefile

本来Makefileのtargetは、依存関係に変更があったときのみ実行されるが、依存に.PHONYのtargetが入っていると、そいつは常に変更されてる判定になって必ずその.PHONYも実行されてしまう
なので、今まで`make server`をすると、`blockchain-node-modules`が必ず変更された判定になるので、それ以降の全て（`blockchain-node-modules`, `$(CONTRACT_ABI_FILE)`, `go-eth-binding`）が毎回実行されて、サーバの起動が毎回面倒だった
今回、`blockchain-node-modules`をファイル名に変え、`go-eth-binding`でもコマンドを実行するのをやめた（真下のファイル名のターゲットで処理を実行するようにした）

.PHONYのmakeターゲットでファイルを生成しないようにする

---

client/src/App.tsx
client/src/apis/knowtfolio.ts
client/src/apis/s3.ts
client/src/components/organisms/Web3Provider/index.tsx
client/src/components/organisms/providers/Web3Provider/index.tsx
client/src/components/pages/EditArticlePage/index.tsx
client/src/components/pages/NewArticlePage/index.tsx
client/src/configs/tinymce.ts
client/webpack.config.js

- Web3Providerを用意して、metamaskを使った認証を行い、metamaskアカウントを提供するProviderを実装した。
- NewArticlePageを実装した
- EditArticlePageを実装した
- webpackの設定を一箇所修正した
- webpackの開発用のサーバーを立てるときに、rootのパスを設定した。
- ↑をしないと、サイト内のパスがすべて相対パスになってしまい、たくさん`404`が発生してしまう

記事作成/編集ページの実装

---

README.md
blockchain/contracts/ERC721URIStorageEnumerableUpgradeable.sol
blockchain/contracts/Knowtfolio.sol
server/services/articles.go
server/services/nfts.go

Closes #42 
* `isOwnerOfArticle`を`getOwnerOfArticle`にして汎用性を少し上げた
* これにより、NFTがない場合は`0x00000...`を返せるようになったので、DELETEでNFTができた後は`OriginalAuthorAddress`をチェックする必要がなくなった
* 検索用エンドポイントを見越して`getArticlesOwnedBy`を追加: #42 
* `mintNFT`のリファクタ
* `_mint`の代わりに`_safeMint`を使うように
* `baseURI`をオーバーライドすることで、引数のURIを不要とした
* ダイヤモンド継承対策
* `ERC721URIStorageEnumerableUpgradeable`を追加することで、関数のコンフリクトを解消するためのオーバーライドを、別のファイルに逃した

Contractのメソッド追加とリファクタ

---

Makefile
docker-compose.yml
entrypoint.sh
server/goa.Dockerfile

#52 の積み残し
* Makefile側で`--entrypoint`を使って指定するようにした（これを忘れていたのでrootで作られたままだった）
* entrypoint.shで、`chown`を使って、WORKDIRの所有権をnon-rootユーザに移すようにした
* ↑を利用して、`goa.Dockerfile`での`go install`の結果がWORKDIRである`/server`以下に入るよう、`GOPATH=/server/go`とした
* これをしないと、↑で`--entrypoint`を指定してもpermission deniedとなってしまう。

Goaファイルの生成も、non-rootユーザで行うように

---

Makefile
docker-compose.yml
server/gateways/api/design/article.go
server/gateways/api/gen/http/openapi3.yaml
server/services/articles.go
server/services/articles_test.go

Closes #45 
今回は小規模な変更なので、designと実装をまとめてやった
また、テストコンテナが機能しない状態になっていたので、docker-compose.ymlとMakefileを少し修正した（積み残し→ #55 ）
現状、Contractの`GetOwnerOfArticle`から0アドレスが返ってきた場合、NFTが存在しないと判断しているが、厳密にはこれだと0x00アドレスの人がサービスを利用できない（使う確率はがどれくらいあるのかわからんが）ので、優先度は低いがissueを立てた： #56

`GET /api/articles/:id`で所有者のアドレスを返すように

---

infrastructure/iam.tf
infrastructure/s3.tf
infrastructure/templates/iam/s3_io_iam_policy.json

以下のリソースを用意した
- `knowtfolio-alpha`というs3 bucket
- cloudfrontからgetが出来るという設定もついている（この点はknowtfolioという名前のs3 bucketと同じ仕様）
- ↑のbucketの`/nfts/`階層のCRUDを行う権限を持つiam user

nftのメタデータ作成用のawsリソース作成

---

Makefile
docker-compose.yml
server/goa.Dockerfile
server/services/articles_test.go
server/services/init_test.go
server/services/nfts_test.go

Closes #55 
* DBやhardhatへの疎通が失敗した時に、Skipするのではなく、Fatalを吐く仕様にし、これらの疎通をしたくない状況では`go test`コマンドのオプションで`-short`を指定すればskipされるようにした
* `sync.Mutex`をアドレスごとに管理し、同じアドレスによるトランザクションが同時並行で発生しないようにした
* これが発生すると、トランザクションに入る`nonce`に不整合が生じ、これによりエラーが発生していた
* goaとgo-eth-bindingをdocker-composeに追加し、Makefileをスッキリさせつつ、`run hardhat`で出ていたエラーを解消

バックエンドテストでtransactionのnonceのエラーを解消

---

docker-compose.yml
server/gateways/api/design/healthcheck.go
server/gateways/api/gen/http/openapi3.yaml
server/main.go
server/services/healthcheck.go
server/services/healthcheck_test.go
server/services/init_test.go

Closes #80 
`GET /health`でサーバの状態を確認できるようにした。
DBやContractとの疎通の確認も行われる。
また、テストの実装時に、Contractとの疎通がないシナリオを再現するために、`docker-compose.yml`でテスト時のプロトコルを`ws`に変え、接続を切断できるようにした（`http`だと接続という概念がないので、`Contract.Close()`を呼んでも切断できない）

ヘルスチェックエンドポイントの追加

---

client/src/App.tsx
client/src/components/pages/NewArticlePage/index.tsx
client/webpack.config.js
infrastructure/cloudfront.tf

close #37 
- 記事の追加・編集ページのフロントエンドでのパスを変更した
- `/new` -> `/articles/new`
- `/:articleId` -> `/articles/:articleId/edit`
- `cloudfront`でも↑似合わせてパスのマッチングパターンを追加した
- `/articles/new`と`/articles/:articleId/edit`の場合はフロントエンドのファイルへ、`/articles/:articleId`の場合はバックエンドのサーバーへ振り分ける設定を追加した。
- 開発者向けに、ローカル環境でフロントとバックエンドの疎通を行うためのproxy設定を追加した。 44a4f67

記事の追加・編集ページのフロントエンドでのパスの変更

---

server/models/article.go
server/services/articles.go
server/services/articles_test.go
server/services/nfts.go
server/services/nfts_test.go
server/services/search.go
server/services/search_test.go

Closes #76 
articleについて、NFTを発行済みかどうかのフラグ`IsTokenized`をDBで管理するようにした。
これにより以下の変更をおこなった。
* `POST /api/nfts/:id`で`IsTokenized`フィールドを更新
* `GET /api/search`で`IsTokenized`を用いた検索
* articlesサービスで`IsTokenized`を用いて認可ロジックを単純化

NFTの有無をDBでも管理

---

client/src/apis/cognito.ts
client/src/components/pages/SignInPage/index.tsx
infrastructure/iam.tf
infrastructure/lambda.tf
infrastructure/templates/iam/basic_lambda_policy.json

- clientで署名によるチャレンジを実装した。
- infrastructureでlambdaに対してcloudwatchのアクセス権限を付与した。
@shugo256  
現時点ではcognitoのcustom challengeが依然として、無条件に成功してしまう状態にある可能性が高い。
- clientで署名をするフローにそもそも行かない
- ↑でもサインインができてしまう
という状況
lambdaでlogは見れるようになったので、少しはデバッグしやすくなったはず

clientとinfraの修正

---

client/src/apis/cognito.ts
infrastructure/function_scripts/auth_challenge/cmd/create/main.go
infrastructure/function_scripts/auth_challenge/cmd/define/main.go
infrastructure/function_scripts/auth_challenge/cmd/verify/main.go
infrastructure/lambda.tf

AWSのコンソールで`custom:wallet_address`をセットした上で、そのアドレスをwalletにセットしてログインページでユーザ名を入力すると、署名を求められて、ログインが成功する。
一方で、`custom:wallet_address`にセットしたものとは別のアドレスで署名すると、ちゃんと失敗する。
また、`custom:wallet_address`をセットしない場合も失敗する
変更点：
* defineと同様にcreateとverifyも実行できるように権限を付与した（コピペ）
* defineで設定していたchallengeNameを`CUSTOM_AUTH`に戻した（こうしないとcreateに進めない（だったらstringではなくenumにしてくれ））
* 認証失敗時にdefineで`FailAuthentication`をtrueにするようにした（こうしないと失敗パターンでは無限ループする）
* ここで、`wallet_address`のフィールドのないユーザに関しては初手で失敗するようにした
* cognito.tsの`signedMessage`が`Promise`になっていて、送信に失敗していたので、`await`をつけた

署名による認証がうまくいった

---

Makefile

-dを使うと、後でまたupした時にコンテナがちゃんと更新されないので

docker-compose up の`-d`オプションを使うのをやめる

---

client/src/apis/knowtfolio.ts
client/src/components/organisms/Header/index.tsx
client/src/components/pages/TopPage/index.tsx
client/webpack.config.js
server/models/article.go
server/models/article_test.go

close #99 
- サイト内を遷移しやすくするリンクを作成した
- ヘッダーの`Knowtfolio`のロゴからトップページに遷移できるようにした
- トップページにあった、遺産とも言える無意味コンテンツを削除し、主要なページへの遷移リンクのリストを表示した
- 記事ページに、記事一覧画面と、記事編集画面への遷移リンクを実装した
-  webpackのproxyの設定を修正した
`/articles`はフロントに飛ばさないといけないが、既存の設定だとバックエンドに飛んで行ってしまう。ワイルドカードを使った設定に追加して乗り越えたかったが、難しそうだったので、少し可読性が落ちるが、関数を使ったカスタムでの実装で修正した。
- バックエンドのエンドポイントの呼び出しのパス指定の微修正
`client/src/apis/knowtfolio.ts`にて、パスの指定を相対パスで行っていたため、絶対パスのような書き方に修正した。（相対パスで指定していると、現在のページのパスからの相対パスで指定することになる）

サイト内の遷移リンクの実装+α

---

client/package-lock.json
client/package.json
client/src/apis/s3.ts
client/src/components/organisms/ArticleEditForm/index.tsx
client/src/components/organisms/ArticleEditor/index.tsx
client/src/components/pages/NewArticlePage/index.tsx

close #103  #105
tinymceのプラグインを利用可能なもののうち、使えそうなものをアドオンした。
- 画像アップロード
- 動画の埋め込み
- リスト
- テーブル
- リンク
- コードブロック
- テキストパターン
などなど
ここで、画像のアップロードには`s3`のapiを用いる必要があるため、この設定をtinymce側でも行った。
テキストパターンはmarkdownチックにタグを生成したりできるが、限界があったので、別で`markdown2html`の機能を今後つける必要がある。#106 に追記しておいた。テキストパターンの限界の詳細は以下
- code block(```で囲むやつ)とリンク(`[]()`で作るやつ)が実装できなかった。
- githubのように、マークダウンで最後までコンテンツを書き上げることができない。(あくまでも、タグの生成を補助するツールとしてしか使えない)
tinymceのeditorのコンポーネントが、新規記事作成画面と記事編集画面で共通化されていなかったので、共通化した。

tinymceのeditorをリッチにした

---

server/services/articles_html.go

`Document`の`Join`のための`Preload`がなされていなかったのが原因

`/articles/:id`でタイトルと本文が読み込まれないバグの修正

---

server/models/document.go

記事をアップロードする際に、DocumentテーブルのRawTextがサイズオーバーしてしまうとmysqlからエラーが出ていたので、対応した。`size`でサイズ(byte?)を直接指定できそうだが、文字数の上限がよくわからなかったので、`type:text`で指定することにした。  
参考：https://gorm.io/docs/data_types.html

Document tableのRawTextのカラムのtypeを変更

---

server/services/search.go
server/services/search_test.go

Closes #176 
今回の症状に対応するテストを追加し、それが通るよう修正した
原因は`SearchForArticles`メソッドで、`baseQuery`をデータ取得用の`loadQuery`と、カウント用の`countQuery`に分岐させていたところで、`Session`メソッドなどの[New Session Method](https://gorm.io/ja_JP/docs/method_chaining.html#New-Session-Method)を呼んでいなかったこと。これを呼ばないと、この箇所のように複数の実行でクエリオブジェクトを共有できないっぽい。

`GET /search`で`owned_by`などの条件指定時に、`total_count`が正しく反映されないことがある問題を修正

---

client/src/components/molecules/ArticleCardBase/index.tsx

- `ArticleCardBase`コンポーネントでのpropsの使い方に問題があった
- onClickのpropsが、`ArticleCardBase`全体に適用されるようになってしまっていた。（本来は記事のタイトル表示の箇所だけに適用させる仕様）
- editボタンを押す → editボタンに指定されている編集ページへの遷移がトリガーされる → カード全体(ArticleCardBaseに対応)に指定されている記事ページへの遷移もトリガーされる → 編集ページ、記事ページと2段階で飛ばされる
- `ArticleCardBase`でonClickのpropsを`ArticleCardBase`全体に適用しないように修正した。

マイページの`Article Collection`に表示されるカードのeditボタンを押すと、編集ページに飛ばないバグの修正

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/organisms/forms/EditArticleForm/index.tsx
client/src/components/organisms/forms/NewArticleForm/index.tsx
client/src/components/organisms/forms/ResetWalletForm/index.tsx
client/src/components/organisms/forms/SignInForm/index.tsx
client/src/components/organisms/forms/SignUpForm/index.tsx
client/src/components/organisms/providers/AuthProvider/index.tsx
client/src/components/organisms/tables/AccountInfoTable/index.tsx

closes #35 
closes #142
- アラートをtoastifyを使ってきれいに表示するようにした
- 画面の自動遷移をいくつかの箇所に実装
- サインイン成功後にマイページへ
- サインアップ成功後にサインアップへ
- `サインアップフォーム -> サインインフォーム` `サインインフォーム -> サインアップフォーム`への導線を実装

アラート関連のUIをToastできれいに

---

client/src/components/organisms/Header/index.tsx

GridというMaterial UIのコンポーネントで`item`というpropsを渡していないというワーニングが出ていたので対応した。  
出ていたwarning
```
react-jsx-runtime.development.js:87 Warning: Failed prop type: The prop `xs` of `Grid` can only be used together with the `item` prop.
```

Girdコンポーネントのpropsの修正

---

infrastructure/function_scripts/pkg/models/sign_up_form.go

closes #218 
原因は記号を含むかどうかのregexが微妙に間違っていて、記号を含まなくてもmatchしてしまっていた点

`sign_up_form`のvalidationで、パスワードに記号を入れたかどうかが判定されていない問題の解消

---

infrastructure/function_scripts/pkg/models/sign_up_form.go

Closes #217 
`validator`の`RegisterTagNameFunc`を使うことで、`validator.FieldError.Field()`の出力をGoのフィールド名（camelケース）からjsonのキーに変更することができた

signupフォームvalidationで、`FieldError.FieldName`の値にjsonのキーを使う

---

server/gateways/api/design/article.go
server/gateways/api/design/search.go
server/gateways/aws/dynamodb.go
server/gateways/ethereum/client.go
server/main.go
server/models/article.go
server/openapi3.yaml
server/services/articles.go
server/services/articles_test.go
server/services/nfts.go
server/services/nfts_test.go
server/services/search.go
server/services/search_test.go

Closes #194
バックエンド側でのユーザのメインの識別子を、wallet addressからuser idに変更した
これによりwalletがなくても記事を作成・編集できるようになる

DBで`articles.OriginalAuthorAddress`をユーザIDに置き換える

---

infrastructure/lambda.tf

Closes #228 
`fileset`の第一引数で`/`を用いた結果、何もマッチしなかったことが原因だったので、素直に`path.module`に変えた
ついでに、`code_diff`がファイルをそのままbase64にかけたものを連結しただけだったので、ファイルの長さに比例するサイズとなって、terraformのログを圧迫していた問題を、`sha256`で固定長にすることで解決した。

terraformのlambdaの`code_diff`トリガーが機能していない問題を修正

---

client/src/apis/knowtfolio.ts
client/src/components/organisms/forms/EditArticleForm/index.tsx
client/src/components/organisms/forms/NewArticleForm/index.tsx
client/src/components/organisms/tables/OwnedArticleTable/index.tsx

Closes #186 
* 記事の作成・更新で署名の代わりにcognitoのidtokenを使うように
* searchで`owned_by`にアドレスではなくユーザidを指定するように (#194 でserver側が変更された)

client側でもCognitoのidtokenを使う

---

server/services/nfts.go
server/services/search.go

`search`, `nfts`共に`Article.OriginalAuthorID`のユーザがaddressを持っていない場合を想定していない挙動となっており、この場合にpanicしてサーバが死ぬバグがあったので、これを修正した

addressを持っていないユーザがいる場合のsearchとnftsのバグ修正

---

Makefile

テストが失敗しても、gha上ではsuccessになってしまっていた（致命的）
`docker compose up`の仕様のせいらしい。`--abort-on-container-exit`オプションをつけることで回避

`make test`のexit codeが、テストが失敗しても0になっていた問題の修正

---

.github/workflows/infrastructure.yml
Makefile

ghaの`infrastructure deploy`は、lambdaのコンパイル時にcontractのbinding(`server/gateways/ethereum/binding.go`に依存するが、ghaのjob実行環境ではこれが生成されていないので失敗していた。
そこで、Makefileの`apply-tf`ターゲットを`go-eth-binding`に依存するようにし（ fc127939fa189db6de9575be9d0d8fc7398c37fc ）、さらに`infrastructure deploy`においても`terraform apply`の前で`make go-eth-binding`するようにした（ a3c832204a2a5112986fd17f4297af3377dbcabc ）。
ついでにMakefileを以下のように修正した
* 6ddb9dbaf94cbce53103800d6a27e3e20617129f コンパイル系のコマンドで、何もしなくていい（ソースが変わっていないなど）時に、生成するはずのファイルのタイムスタンプが更新されず、makeで毎回コンパイルが呼ばれてしまう問題があった。何もしなくていい時でも`touch`をつかってタイムスタンプだけは更新するようにした。
* 50a9c63c9fe08b3178f0144517e52a4bffe807fa `docker-compose`ではなく`docker compose`を使うようにした
* 6c505bffa4b22e48c15dce8b87bfa7b6208f9fce `docker compose run`の時に毎回コンテナが残って、気づいた時にはたくさん残骸が残っているのを解消するために、`--rm`オプションを追加
**※ merge後 `make clean` …

golangのcontractのbindingがないために、ghaでの`apply-tf`が失敗する問題の修正

---

Makefile
server/goa.Dockerfile

* goaのバージョンは今までざっくりv3と指定していたが、最近のアップデートによりgo1.20以上を要求するようになったため、アプデ前のv3.11.1で固定した
* 本来はgoのversionをあげればいいが、取り急ぎ
* #255 で使われていないと思っていたmakeターゲットである`client/dist`を削除したが、これは実は`client build`のworkflowで使われていたので復活させた

ghaで出ていたエラーを修正

---

client/src/apis/dynamodb.ts
client/src/apis/knowtfolio.ts
client/src/components/organisms/forms/NewArticleForm/index.tsx
client/src/components/organisms/forms/RegisterWalletForm/index.tsx
infrastructure/function_scripts/cmd/create_auth_challenge/main.go
infrastructure/function_scripts/cmd/verify_auth_challenge_response/main.go
infrastructure/function_scripts/pkg/models/post_wallet_address_request.go
infrastructure/function_scripts/pkg/models/validation.go
server/gateways/aws/dynamodb.go
server/gateways/ethereum/verify_signature.go
server/services/articles_test.go
server/services/init_test.go
server/services/nfts.go
server/services/nfts_test.go
server/services/search_test.go

アドレス登録（`post_wallet_address`）時はnonceが生成されていない& どのみち一度しかできない操作なので、nonceなしの署名のままにしてある

アドレス登録時以外の全ての署名でnonceを使用する

---

client/src/components/organisms/forms/helper.tsx
infrastructure/function_scripts/pkg/models/sign_up_form.go
infrastructure/function_scripts/pkg/models/validation.go

Closes #234 
Cognito自体は任意の言語の文字を許容していそう（参考： https://stackoverflow.com/questions/44179337/usernames-regular-expression-in-aws-cognito ）だが、lambdaでのvalidationでは、より厳しく、githubと同様の制約とした（参考： https://qiita.com/KEINOS/items/34041c94913b7bed7431 ）

サインアップ時に、`username`の形式をチェック
