team-azb/knowtfolio

server/gateways/api/design/api.go, server/gateways/api/design/article.go, server/gateways/api/design/article_html.go
=> サービス名とパスを複数形に

server/gateways/api/design/api.go, server/gateways/api/design/nft.go, server/gateways/api/gen/http/openapi3.yaml
=> NFTサービスのDesign

README.md
=> READMEに説明を追加

blockchain/contracts/Knowtfolio.sol
=> BaseURIをjson metadataのパスに変更

client/src/apis/cognito.ts, infrastructure/iam.tf, infrastructure/lambda.tf, infrastructure/templates/iam/knowtfolio_auth_challenge_lambda_assume_policy.json
- `AccessDeniedException`のエラーは[stack overflowのQ&A](https://stackoverflow.com/questions/66246886/cognito-user-pool-lambda-trigger-permission)で解決できた。  
- clientを`custom challenge`に対応した
=> custom challengeのcognito対応(残り分) + clientの対応

Makefile
=> Makefileのappの依存関係を修正

server/gateways/api/design/api.go, server/gateways/api/design/article.go, server/gateways/api/design/article_html.go, server/gateways/api/design/question.go, server/gateways/api/design/search.go, server/gateways/api/gen/http/openapi3.yaml, server/services/articles.go, server/services/articles_html.go
#107 の一部
`author_address`は今後（NFTのMint以外は）署名による認証からCognitoによる認証に切り替わりそうなので、一旦なしとした。
また、ベストアンサーIDなども、まだ仕様が詰まっていないので機能追加のたびにその都度追加するスタイルで行く
=> 質問サービスのdesign

client/src/components/organisms/WalletAddressDisplay/index.tsx, client/src/components/organisms/forms/ResetWalletForm/index.tsx, client/src/components/pages/AccountPage/index.tsx, client/src/components/pages/ResetWalletPage/index.tsx
マイページ(`/mypage`)とwallet addres再設定画面(`/reset-wallet`)のUIを実装した。
=> マイページのUIを実装

infrastructure/ec2.tf, infrastructure/rds.tf
- RDSを作成した
- ec2で、↑のRDSと疎通をするための設定を追加した
=> RDSにデータベースを移行した

client/src/apis/cognito.ts, infrastructure/cognito.tf, infrastructure/dynamodb.tf, infrastructure/function_scripts/cmd/define_auth_challenge/main.go, infrastructure/function_scripts/cmd/post_confirmation/main.go, infrastructure/function_scripts/cmd/pre_sign_up/main.go, infrastructure/function_scripts/cmd/validate_sign_up_form/main.go, infrastructure/function_scripts/cmd/verify_auth_challenge_response/main.go, infrastructure/function_scripts/go.mod, infrastructure/function_scripts/go.sum, infrastructure/function_scripts/pkg/aws_utils/config.go, infrastructure/iam.tf, infrastructure/lambda.tf, infrastructure/templates/iam/basic_lambda_policy.json
=> Lambdaでの`wallet_address`の利用をcognitoからdynamodbに切り替える

infrastructure/ec2.tf
=> バックエンドのインスタンスを`t2.micro`に

server/services/articles.go
Closes #197 
元々DBの保存内容自体をsanitizeするつもりだったが、sanitizerの設定を変えた時に、既存のデータが全て復元できなくなる可能性があるので、DBの中身はそのままとした
`Article.Document.Content`の代わりに`Article.Document.SanitizedContent()`を置き換えた。
また、この挙動で統一するために、`articleXXToResult`系のメソッドを一つにまとめ、↑の変更が一か所で済むようにした。
=> `/api/articles`でもsanitizeしたcontentを返す

.github/workflows/server.yml
=> `article_template.html`をdeployのartifactsに追加

infrastructure/function_scripts/pkg/models/validation.go
#174 でマージするときに消えてしまっていた（#220）を復元した。
=> #174 のマージの際に #220 が漏れていたので修正

client/src/components/organisms/forms/EditArticleForm/index.tsx, client/src/components/organisms/forms/NewArticleForm/index.tsx
Lintのwarnignsが出ている箇所が放置されていたので修正
=> Lintのwarningsを対応

client/src/apis/cognito.ts, client/src/components/organisms/forms/ResetProfileForm/index.tsx, client/src/components/organisms/forms/SignUpForm/index.tsx, client/src/components/organisms/forms/helper.tsx, client/src/components/organisms/providers/AuthProvider/index.tsx, client/src/components/organisms/tables/MyAccountInfoTable/index.tsx, infrastructure/cognito.tf, infrastructure/function_scripts/cmd/pre_sign_up/main.go, infrastructure/function_scripts/cmd/validate_sign_up_form/main.go, infrastructure/function_scripts/go.mod, infrastructure/function_scripts/go.sum, infrastructure/function_scripts/pkg/models/sign_up_form.go, infrastructure/lambda.tf, server/gateways/aws/cognito.go, server/services/init_test.go
closes #227 
- infraでcognitoのスキーマの変更
- lambdaでビルドが失敗したらapplyが終了するように修正
- serverでテストを書き換え
- clientでフォームの入力項目の変更
=> cognitoのユーザーの検証項目を電話番号からEmailに変更

client/src/apis/dynamodb.ts
#253 でフロント側の修正が一箇所漏れていたので対応した。
=> clientのdynamodbからの値の取得のキーの修正

client/src/components/organisms/forms/SearchForm/index.tsx
=> クエリパラメータと検索窓の入力が不一致になるバグ修正

server/services/articles.go, server/services/articles_test.go, server/services/init_test.go, server/services/nfts_test.go, server/services/search_test.go
=> walletのないユーザが作成した記事が取得できない問題の解消

client/src/components/organisms/tables/MyOwnedArticlesTable/index.tsx
=> コレクションをリロードするボタンの配置
